apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: readfile
    name: readfile
  name: readfile-deployment
spec:
  selector:
    matchLabels:
      app: readfile
  template:
    metadata:
      labels:
        app: readfile
    spec:
      containers:
      - name: readfile
        image: phuongdn2202/test-app-minikube:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: readfile-svc
spec:
  type: ClusterIP
  selector:
    app: readfile
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: readfile
    
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: svc-oauth2
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
spec:
  ingressClassName: nginx
  rules:
  - host: readfile.local
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: release-name-oauth2-proxy
            port:
              number: 80
  - host: www.readfile.local
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: release-name-oauth2-proxy2
            port:
              number: 80
  tls:
  - hosts:
    - readfile.local
    - www.readfile.local
    secretName: tls-readfile-local
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.home.arpa/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=https://auth.home.arpa/"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
  name: external-auth-readfile
spec:
  ingressClassName: nginx
  rules:
  - host: readfile.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: readfile-svc
            port:
              number: 80
      - path: /svc2
        pathType: Prefix
        backend:
          service:
            name: readfile-svc2
            port:
              number: 80
  #tls:
  #- hosts:
    #- vvv.readfile.local
    #- www.readfile.local
    #secretName: tls-readfile-local
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://auth.instance2.arpa/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://www.readfile.local/oauth2/start?rd=https://auth.instance2.arpa/"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "64k"
  name: external-auth-svc2
spec:
  ingressClassName: nginx
  rules:
  - host: www.readfile.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: readfile-svc2
            port:
              number: 80
  #tls:
  #- hosts:
    #- vvv.readfile.local
    #- www.readfile.local
    #secretName: tls-readfile-local
       
              
              
