apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: readfile2
    name: readfile2
  name: readfile-svc2-deployment
spec:
  selector:
    matchLabels:
      app: readfile2
  template:
    metadata:
      labels:
        app: readfile2
    spec:
      containers:
      - name: readfile2
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: readfile-svc2
spec:
  type: ClusterIP
  selector:
    app: readfile2
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: readfile2
    
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: external-auth-readfile-svc2
spec:
  ingressClassName: nginx
  rules:
  - host: readfile-svc2.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: readfile-svc2
            port:
              number: 80
